export const browserCoreExamples = [
  "openhoof browser status",
  "openhoof browser start",
  "openhoof browser stop",
  "openhoof browser tabs",
  "openhoof browser open https://example.com",
  "openhoof browser focus abcd1234",
  "openhoof browser close abcd1234",
  "openhoof browser screenshot",
  "openhoof browser screenshot --full-page",
  "openhoof browser screenshot --ref 12",
  "openhoof browser snapshot",
  "openhoof browser snapshot --format aria --limit 200",
  "openhoof browser snapshot --efficient",
  "openhoof browser snapshot --labels",
];

export const browserActionExamples = [
  "openhoof browser navigate https://example.com",
  "openhoof browser resize 1280 720",
  "openhoof browser click 12 --double",
  'openhoof browser type 23 "hello" --submit',
  "openhoof browser press Enter",
  "openhoof browser hover 44",
  "openhoof browser drag 10 11",
  "openhoof browser select 9 OptionA OptionB",
  "openhoof browser upload /tmp/openhoof/uploads/file.pdf",
  'openhoof browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "openhoof browser dialog --accept",
  'openhoof browser wait --text "Done"',
  "openhoof browser evaluate --fn '(el) => el.textContent' --ref 7",
  "openhoof browser console --level error",
  "openhoof browser pdf",
];
