#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${OPENHOOF_INSTALL_E2E_IMAGE:-${HOOFBOT_INSTALL_E2E_IMAGE:-openhoof-install-e2e:local}}"
INSTALL_URL="${OPENHOOF_INSTALL_URL:-${HOOFBOT_INSTALL_URL:-https://openhoof.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
OPENHOOF_E2E_MODELS="${OPENHOOF_E2E_MODELS:-${HOOFBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e OPENHOOF_INSTALL_URL="$INSTALL_URL" \
  -e OPENHOOF_INSTALL_TAG="${OPENHOOF_INSTALL_TAG:-${HOOFBOT_INSTALL_TAG:-latest}}" \
  -e OPENHOOF_E2E_MODELS="$OPENHOOF_E2E_MODELS" \
  -e OPENHOOF_INSTALL_E2E_PREVIOUS="${OPENHOOF_INSTALL_E2E_PREVIOUS:-${HOOFBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e OPENHOOF_INSTALL_E2E_SKIP_PREVIOUS="${OPENHOOF_INSTALL_E2E_SKIP_PREVIOUS:-${HOOFBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
